---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/nfiniut0/infinityCRM/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp preload.php $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH